### ISSUE TITLE
Replace deprecated sheet opening method in dialogs.py.

### ISSUE THREAD

**Issue by typesupply** [typesupply/vanilla#11]
This is the deprecated method:

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSApplication_Class/DeprecationAppendix/AppendixADeprecatedAPI.html#//apple_ref/occ/instm/NSApplication/beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:

**Comment by justvanrossum** [comment]
That link doesn't work as nicely anymore. I suppose it's about these calls
- https://developer.apple.com/documentation/appkit/nsalert/1532128-beginsheetmodalforwindow?language=objc
- https://developer.apple.com/documentation/appkit/nssavepanel/1539011-beginsheetfordirectory?language=objc
- https://developer.apple.com/documentation/appkit/nsopenpanel/1584367-beginsheetfordirectory?language=objc
