### ISSUE TITLE
Bug triggered by drag and drop

### ISSUE THREAD

**Issue by fsi-jens** [typesupply/vanilla#12]
I think I found a bug when dragging/dropping onto a list ... see a demo script for RoboFont here: https://gist.github.com/fsi-jens/3ef12361015f84cbc418

Dragging the color onto the list will trigger the bug.

``````
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaList.py", line 164, in tableView_validateDrop_proposedRow_proposedDropOperation_
    return self._handleDrop(True, tableView, draggingInfo, row, dropOperation)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaList.py", line 110, in _handleDrop
    if window is not None and draggingSource is not None and window == draggingSource.window() and vanillaWrapper._selfWindowDropSettings is not None:
AttributeError: No attribute window```
``````

**Comment by typemytype** [comment]
this is still an issue

proposal:

List drag and drop has been build with the assumption that a dragging source is a table view and that is maybe not correct. In this case the dragging source is an `NSColorPanel`.

Test if the source is has a window, if not: alway use the otherApplicationDropSettings... Its not completely correct, as its possible to have multiple colorwells in different windows that could drop in specified tableviews..., but the validation is in those cases up to the script instead handleDrop of the vanilla list...
