### ISSUE TITLE
CheckBox sizeStyle='small'

### ISSUE THREAD

**Issue by Mark2Mark** [typesupply/vanilla#22]
Any chance to have this setting not shift the Text up (as opposed to vertically centered in `sizeStyle='regular'`)?

<img width="349" alt="screen shot 2016-03-08 at 17 14 00" src="https://cloud.githubusercontent.com/assets/5824595/13607645/6866246c-e551-11e5-8bda-7a9b8f4dbf11.png">

**Comment by typesupply** [comment]
This has been driving me crazy for close to a decade. It's a Cocoa issue and I have no idea why it happens. Details are in the code here: https://github.com/typesupply/vanilla/blob/master/Lib/vanilla/vanillaCheckBox.py

**Comment by Mark2Mark** [comment]
Interesting. Thanks for the info. I thought the `frameAdjustments`plus `textBoxPosSize ` are therefore there. So since you’re aware of this, I suppose that hacking into the height value of the latter doesn’t help in any way?

**Comment by Mark2Mark** [comment]
[referencing to my pull request which might solve it](https://github.com/typesupply/vanilla/pull/36) to make the alignment work better.
