### ISSUE TITLE
AccessibilityTitle

### ISSUE THREAD

**Issue by Mark2Mark** [typesupply/vanilla#25]
My recently created pull request is just a proposal of course.
If there is another way, to get the index of each PopUpButton in a dynamically created sequence of Buttons, I’d be happy to know about.

Currently I am sneaking the indexes inside the Button Items (pretty ugly):
<img width="502" alt="screen shot 2016-03-22 at 16 39 23" src="https://cloud.githubusercontent.com/assets/5824595/13957441/c5cdfdb8-f04c-11e5-8c0d-a4131a0b9116.png">

**Comment by Mark2Mark** [comment]
In the meantime I could manage to add these 2 functions to a Vanilla Object on the fly. So if this is a too special need, please nevermind to ignore implementing it in general:


```
from vanilla import *

class AccessibilityTitleDemo(object):

	def __init__(self):

		#------------------------------------------------------
		### Create custom functions to [PopUpButton] Class:
		def __setAccessibilityTitle(self, customTitle):
			self._nsObject.setAccessibilityTitle_(customTitle)

		def __accessibilityTitle(self):
			return self._nsObject.accessibilityTitle()
		
		### Add custom functions to [PopUpButton] Class:
		PopUpButton.setAccessibilityTitle = __setAccessibilityTitle
		PopUpButton.accessibilityTitle = __accessibilityTitle
		#------------------------------------------------------

		self.w = Window((150, 70))

		#------------------------------------------------------
		self.w.b = PopUpButton((10, 10, -10, 20), ["Item 1", "Item 2"], callback=self.PBCallback)
		self.w.b.setAccessibilityTitle("1")

		self.w.c = PopUpButton((10, 40, -10, 20), ["Item 1", "Item 2"], callback=self.PBCallback)
		self.w.c.setAccessibilityTitle("2")
		#------------------------------------------------------		

		self.w.open()

	def PBCallback(self, sender):
		print "PopUpButon: %s - %s" % ( sender.accessibilityTitle(), sender.getTitle() )

AccessibilityTitleDemo()
```

**Comment by andyclymer** [comment]
Hey Mark, your question is a little old but maybe you're still looking for an answer? This is how Tal showed me to do it once — set an "id" attribute for a control, and then have the callback check the "id" of the sender.

```
from vanilla import *

class PopUpTest(object):
    
    def __init__(self):
        
        self.w = Window((200, 100), "Test")
        self.w.button1 = PopUpButton((10, 10, -10, 20), ["Item 1", "Item 2"], callback=self.myCallback)
        self.w.button1.id = "Number choices"
        self.w.button2 = PopUpButton((10, 40, -10, 20), ["Item A", "Item B"], callback=self.myCallback)
        self.w.button2.id = "Letter choices"
        self.w.text = TextBox((10, 70, -10, 20), "Button:")
        self.w.open()
        
    def myCallback(self, sender):
        infoText = "Button: " + str(sender.id)
        self.w.text.set(infoText)
        
PopUpTest()
```

**Comment by Mark2Mark** [comment]
Hey Andy, thanks for your hint on that. For some reason I couldn’t find the `.id`which is indeed exactly what was needed. Anyway I dug myself into monkey patching and implemented it the way described above. Yours is way shorter and cleaner of course, so I’ll probably rewrite my stuff. Thanks so much again, Andy.
