### ISSUE TITLE
Checkbox labels are not aligned

### ISSUE THREAD

**Issue by schriftgestalt** [typesupply/vanilla#34]
I noticed that checkbox labels are not vertically aligned with the text. It happens because the label is a separate text field, instead of just setting the title property of the checkbox button. The Header states that it was done to fix an alignment problem but that is fixed by now (at least in 10.12). In 10.9 the default it not 100% perfect but better than the manually set version. So the workaround should be removed.

**Comment by Mark2Mark** [comment]
Appart from this issue being solved with 10.12 I think the workaround values are just off a bit. I created [this pull request](https://github.com/typesupply/vanilla/pull/36) to make the alignment work better.

**Comment by justvanrossum** [comment]
Indeed, see #36, I'll close this for now.
