### ISSUE TITLE
TextEditor selection callback

### ISSUE THREAD

**Issue by typoman** [typesupply/vanilla#35]
Hi all,

I've been trying to find a method to get callbacks while the selection changes in a NSTextView instance which a vanilla TextEditor is wrapped around, something like 'NSTextViewDidChangeSelection' notification but I can't find a method on how this could be implemented in PyObjC. Does anyone here know how this is done?

Thanks

**Comment by typemytype** [comment]
you will have to subclass a fresh text view delegate and add a method called 

```python

from vanilla.vanillaTextEditor import VanillaTextEditorDelegate, TextEditor

class CustomVanillaTextEditorDelegate(VanillaTextEditorDelegate):

    def textViewDidChangeSelection_(self, notification):
        # do something when the selection changed


class CustomTextEditor(TextEditor):

    delegateClass = CustomVanillaTextEditorDelegate
```

(untested but should work..)

also see 
* https://github.com/typesupply/vanilla/blob/master/Lib/vanilla/vanillaTextEditor.py#L6
* https://developer.apple.com/reference/appkit/nstextviewdelegate/1449363-textviewdidchangeselection?language=objc

**Comment by typoman** [comment]
Thank you very much, it works! The only problem is that when I try to execute the script second time I get a Traceback:
`error: CustomVanillaTextEditorDelegate is overriding existing Objective-C class`

Is there anyway to avoid this?

**Comment by typoman** [comment]
I realized I can avoid overriding the delegate class by not importing it from another module but still binding the textViewDidChangeSelection_ to a callback inside the CustomTextEditor seems tricky, I'm trying to figure out a way to add another callback to the TextEditor. I will post it here if I found a neat way to do it.

**Comment by typoman** [comment]
This is how I did it. Thank you very much!
```

from vanilla.vanillaTextEditor import VanillaTextEditorDelegate, TextEditor
from vanilla.vanillaBase import VanillaCallbackWrapper


class CostumVanillaTextEditorDelegate(VanillaTextEditorDelegate):

    def textViewDidChangeSelection_(self, notification):
        if hasattr(self, "_targetselection"):
            textView = notification.object()
            self._targetselection.action_(textView)


class CostumTextEditor(TextEditor):

    delegateClass = CostumVanillaTextEditorDelegate

    def __init__(self, *args, **kwargs):
        super(CostumTextEditor, self).__init__(*args, **kwargs)

    def setSelectionCallback(self, callback):
        if callback is not None:
            self._targetselection = VanillaCallbackWrapper(callback)
            delegate = self._textView.delegate()
            if delegate is None:
                self._textViewDelegate = delegate = self.delegateClass.alloc().init()
                self._textView.setDelegate_(delegate)
            delegate._targetselection = self._targetselection

    def getSelection(self):
       """
       Get the selected text.
       """
       selStart, selLength = self._textView.selectedRange()
       return selStart, selLength

```
