### ISSUE TITLE
How can I make a vertical slider?

### ISSUE THREAD

**Issue by frankrolf** [typesupply/vanilla#58]
Reading the code [here](https://github.com/typesupply/vanilla/blob/024ba95c971c8b3f82bca9c6b231cc4af15875c0/Lib/vanilla/vanillaSlider.py#L149-L154), I would expect this slider to be vertical.
It isn’t! What am I doing wrong?

```
from vanilla import *

class Vertical_Slider(object):

     def __init__(self):
         self.w = Window((60, 200))
         self.w.slider = Slider(
             (25, 10, 10, -10))
         self.w.open()

Vertical_Slider()
```

**Comment by justvanrossum** [comment]
Hm, a vertical slider is what I'm getting on 10.10:

![image](https://user-images.githubusercontent.com/4246121/35792837-57093694-0a4f-11e8-9910-623234915e13.png)

**Comment by justvanrossum** [comment]
I can't find any changes regarding `NSSlider` on 10.13 that could explain a change in behavior. Can you check what happens if you run this in DrawBot?

**Comment by frankrolf** [comment]
![screen shot 2018-02-05 at 00 26 31](https://user-images.githubusercontent.com/2049645/35794619-4f0d1954-0a0b-11e8-91e9-56d8cdde7530.png)
This is DrawBot 3.114 on 10.13.3.

**Comment by justvanrossum** [comment]
Thanks. Seems like an OS issue :(

@typemytype, what do you think?

**Comment by typemytype** [comment]
this works:

```python
from vanilla import *

class Vertical_Slider(object):

    def __init__(self):
        self.w = Window((60, 200))
        self.w.slider = Slider(
             (25, 10, 10, -10))
        # setting is vertical explicit
        self.w.slider.getNSSlider().setVertical_(True)
        
        self.w.open()

Vertical_Slider()
```

I would propose to set `isVertical_` during init of the slider object

**Comment by typemytype** [comment]
the same logic as this could be used: https://github.com/typesupply/vanilla/blob/master/Lib/vanilla/vanillaSlider.py#L148-L149

**Comment by typemytype** [comment]
or it could be an new argument... (I prefer the first option as it will not break anything)

**Comment by justvanrossum** [comment]
Your fix is fine, there seems to be no need to be explicit about the orientation.

**Comment by typemytype** [comment]
have to test on 10.11 and 10.12
dont know where the change happened...

**Comment by typemytype** [comment]
it does not work from 10.11...

**Comment by typemytype** [comment]
a change from 10.12 see https://developer.apple.com/library/content/releasenotes/AppKit/RN-AppKitOlderNotes/index.html


> NSSlider isVertical
> 
> NSSlider and NSSliderCell's `vertical` property is now readwrite and has changed its type from NSInteger to BOOL. In previous releases, NSSliderCell would try to automatically determine its orientation based on the aspect ratio of a received cell frame. This also led to -1 being returned from `isVertical` if it could not make a determination (e.g. the cell frame had a zero size), and could lead to the slider changing orientation when it was resized.
> 
> With 10.12, the vertical property is set at initialization time based on the aspect ratio of the frame parameter, and defaults to horizontal in ambiguous (equal width/height) cases; however it is recommended to explicitly set the vertical property or use the convenience constructors. To dynamically change the orientation of the slider, explicitly set the `vertical` property.

**Comment by frankrolf** [comment]
Thank you!
