### ISSUE TITLE
Positioning broken in SplitView

### ISSUE THREAD

**Issue by colinmford** [typesupply/vanilla#69]
Hey all, 

Long time listener, first time caller. I think I have found a bug in SplitView but I don't know enough about it to track it down. I can see through the commits that it recently has had some work done to move it away from RBSplitView to NSSplitView, so maybe @justvanrossum might have some idea what's going on.

I noticed at first because I was trying to port over some scripts to RF3, which has a more recent version of Vanilla, I assume, than 1.8.4.

Run the below in RoboFont 1.8.4 and RoboFont 3.0:
```python
from vanilla import Window, SplitView, Box, TextBox

class GroupDemo(object):
    def __init__(self):
        self.w = Window((500, 500), minSize=(10,10))
        
        self.panel1 = Box((20, 20, -20, -20))
        self.panel1.text = TextBox((0, 0, -0, -0), "This is a box")
        
        self.panel2 = Box((20, 20, -20, -20))
        self.panel2.text = TextBox((0, 0, -0, -0), "This is a box, also")

        panes = [
            dict(view=self.panel1, identifier="panel1"),
            dict(view=self.panel2, identifier="panel2"),
        ]
        self.w.splitView = SplitView((0, 0, -0, -0), panes)
        
        self.w.open()

GroupDemo()
```

In RF 1.8.4, with a previous version of Vanilla (I can't know which, since `__version__` was just added), I get what I would expect: two panels with a box inside, with a 20px "margin"

![image](https://user-images.githubusercontent.com/671409/39023051-735f03aa-4406-11e8-9d40-d3d7b03217a2.png)

In RF 3.0, and a newer version of Vanilla, I get a boxes that fill the entire panel. No matter what `posSize` I make the Box (or Group, or Button, TextBox, etc), it will stay the same size and position.

![image](https://user-images.githubusercontent.com/671409/39023100-b5237032-4406-11e8-8dcd-4201a1139900.png)

"OK", I thought, "maybe I'll just add a sacrificial group to act as the panel container". Things get better, but still act strange:
```python
from vanilla import Window, SplitView, Box, Group, TextBox


class GroupDemo2(object):
    def __init__(self):
        self.w = Window((500, 500), minSize=(10,10))
        
        self.panel1 = Group((0, 0, -0, -0))
        self.panel1.box = Box((20, 20, -20, 50))
        self.panel1.box.text = TextBox((0, 0, -0, -0), "This is a box with absolute height")
        
        self.panel2 = Group((0, 0, -0, -0))
        self.panel2.box = Box((20, 20, -20, -20))
        self.panel2.box.text = TextBox((0, 0, -0, -0), "This is a box with relative height")

        panes = [
            dict(view=self.panel1, identifier="panel1"),
            dict(view=self.panel2, identifier="panel2"),
        ]
        self.w.splitView = SplitView((0, 0, -0, -0), panes)
        
        self.w.open()

GroupDemo2()
```

The box with the absolute height is positioned as I would expect, yay! But the relative height box runs off the top.

![image](https://user-images.githubusercontent.com/671409/39023575-847a54de-4409-11e8-842a-0ca940301853.png)

It may be a misunderstanding I have about how SplitView is supposed to work now, but I feel like something is wrong here. Even the demo code included in `vanillaSplitView.py` displays differently from version to version.

Thanks!

**Comment by justvanrossum** [comment]
But I tried to apply all wrokarounds/hacks for #47, and none worked for this case, so I'm stuck :(

**Comment by typemytype** [comment]
the old rb split view had a view in-between... The problem starts here I guess https://github.com/typesupply/vanilla/blob/master/Lib/vanilla/vanillaSplitView.py#L188-L189

**Comment by typemytype** [comment]
I guess this could fix it https://github.com/typesupply/vanilla/commit/283c5b4520292160d57f71241a1bc3cd5d5332bc

in branch https://github.com/typesupply/vanilla/tree/splitview_fix

**Comment by typemytype** [comment]
the second example is the more correct with a `vanilla.Group((0, 0, -0, -0))` as the first pane view. This makes sense as a SplitView needs a flexible scalable first view inside.

**Comment by justvanrossum** [comment]
> I guess this could fix it 283c5b4

Hm, I don't see a difference.

**Comment by colinmford** [comment]
Wow! Thanks for tracking this down, guys!

**Comment by justvanrossum** [comment]
Discussion continues at #70
