### ISSUE TITLE
Slider is vertical when width > height

### ISSUE THREAD

**Issue by jtanadi** [typesupply/vanilla#84]
Seems like there's a small bug in `Slider._isVertical()`. When `w` is larger than `h`, `Slider._isVertical()` returns `True` when it should be `False` (ie. wider objects shouldn't be vertical).

**Comment by typemytype** [comment]
is this still an issue?

**Comment by justvanrossum** [comment]
Well, `slider._isVertical()` indeed seems to return the opposite of what its name suggests.

**Comment by justvanrossum** [comment]
```python
from vanilla import *

w = Window((200, 200))
w.sl1 = Slider((20, 20, 80, 20))
w.sl2 = Slider((20, 50, 20, 80))
w.open()

print(w.sl1._isVertical())
print(w.sl2._isVertical())
```

**Comment by gferreira** [comment]
yep, still an issue. it works correctly only if the slider width is defined as a negative number.

**Comment by typemytype** [comment]
I see, maybe it should not be calculated from the posSize of the slider view at all.

Proposal `isVertical ` keyword in the init, so users can set it deliberately.
The width can be negative (meaning the view becomes resizable)

like `Slider(posSize, isVertical=True/False`) 

as default `isVertical` fallbacks to `False` as most sliders are indented to be horizontal.

this value will otherwise always be ambiguous

**Comment by gferreira** [comment]
sounds good to me. `RadioGroup` already works like this.

**Comment by typemytype** [comment]
yep, `RadioGroup` and `SplitViews` have this key word already and there is no confusion :)

**Comment by jtanadi** [comment]
Curious if `_isVertical()` could check if the width passed in is negative, or maybe this is still not explicit enough.

```python
def _isVertical(self):
    # based on the pos size return if the slider is vertical or not.
    w, h = self._posSize[2:]
    if w < 0:
        return w >= h
    return w < h
```

`Slider((10, 10, 20, 10))` --> horizontal
`Slider((10, 10, 10, 20))` --> vertical
`Slider((10, 10, -10, 10))` --> horizontal
`Slider((10, 10, -20, 10))` --> horizontal
`Slider((10, 10, -10, -20))` --> vertical
`Slider((10, 10, 0, 20))` --> vertical
`Slider((10, 10, 0, -20))` --> horizontal (should it be?)

**Comment by typemytype** [comment]
fixed
