### ISSUE TITLE
More precisely target cell when editing List

### ISSUE THREAD

**Issue by jtanadi** [typesupply/vanilla#86]
Hi, is there a way to more precisely "target" a specific cell in a `List`?

For example, in a List like this:
<img width="379" alt="screen shot 2018-11-21 at 6 55 07 am" src="https://user-images.githubusercontent.com/18740288/48839778-8ccec200-ed5a-11e8-8236-532dcfd3b0f1.png">

To get the value of the "Type size" cell in row 1, I would do something like this in my `editcallback`:
```python
selectedIndex = self.w.myList.getSelection()[0]
newSize = self.w.myList[selectedIndex]["typeSize"]
```
vs. something like this, if possible:
```python
selectedCellIndex = self.w.myList.getCell()
```

Thanks!

**Comment by typemytype** [comment]
There is a lot going on in the middle between your list of dictionaries and the vanilla List. 

cells are just representation of data... they aren't the real item from your list. A cell is also reused over and over again in the list view (a NSTableView). 

I make a convenience method in the my controller to get the selected item of a vanilla List. This can be used inside a edit callback but also elsewhere

good luck

**Comment by jtanadi** [comment]
ah, good to know. I just thought I was missing out on something.

thanks as always for the help!
